site_name: nats-nsc documentation
theme:
    name: readthedocs
    highlightjs: true

nav:
  - Basics: index.md
  - nats_nsc module reference: nats_nsc_module.md


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          preload_modules: __all__
          load_external_modules: true
          show_if_no_docstring: true
          paths:
            - src
          group_by_category: true
