# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package and Build Docs

on:
  workflow_dispatch:
  release:
    types: [published]


permissions:
  contents: read
  packages: write

jobs:
  build:
    environment:
      name: pypi
      url: https://pypi.org/p/nats-nsc
    permissions:
      id-token: write 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install dependencies
      run: pdm install --dev
    - name: Build package
      run: pdm build -v
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: build docs
      run: pdm run mkdocs build
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: site
  docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pdm install --dev
      - name: Build package
        run: pdm build -v
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: build docs
        run: pdm run mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site