# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: [workflow_dispatch]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    environment:
      name: pypi
      url: https://pypi.org/p/nats-nsc
    permissions:
      id-token: write 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install dependencies
      run: pdm install
    - name: Build package
      run: pdm build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
